export const Action = {
  SAVE_ALL_PACKAGE: "SAVE_ALL_PACKAGE",
};

export const User = {
  LOG_IN: "USER_LOGGED_IN",
  SIGN_UP_WITHOUT_PASSWORD: "USER_SIGN_UP_WITHOUT_PASSWORD",
  LOG_OUT: "USER_LOGGED_OUT",
  UPDATE_INFO: "UPDATE_USER_PROFILE_DATA",
};

export const Order = {
  STORE_LOGO_ORDER_DATA: "STORE_DATA_FOR_LOGO_ORDER_IN_REDUCER",
  CLEAR_ORDER_REDUCER: "CLEAR_ORDER_REDUCER",
};

/**
 * All authorization is done in single modal named as signup modal
 */
export const ModalConstant = {
  OPEN_SIGN_UP_MODAL: "OPEN_SIGN_UP_MODAL",
  OPEN_SIGN_UP_MODAL_ORDER_CREATE: "OPEN_SIGN_UP_MODAL_ORDER_CREATE",
  OPEN_LOGIN_MODAL: "OPEN_SIGN_UP_MODAL_FOR_LOGIN",
  CLOSE_SIGN_UP_MODAL: "CLOSE_SIGN_UP_MODAL",
};

export const Cart = {
  OPEN: "OPEN_CART",
  CLOSE: "CLOSE_CART",
};
